// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioThermometer.Infrastructure.Data;

#nullable disable

namespace PortfolioThermometer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<string>("CrmExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_external_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("ResolvedDate")
                        .HasColumnType("date")
                        .HasColumnName("resolved_date");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_complaints_created_date");

                    b.HasIndex("CrmExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_complaints_crm_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_complaints_customer_id");

                    b.HasIndex("ResolvedDate")
                        .HasDatabaseName("idx_complaints_resolved_date");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_complaints_severity");

                    b.ToTable("complaints", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_renew");

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_type");

                    b.Property<string>("CrmExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_external_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("MonthlyValue")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monthly_value");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CrmExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_contracts_crm_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_contracts_customer_id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("idx_contracts_end_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_contracts_status");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountManager")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("account_manager");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CrmExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_external_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("OnboardingDate")
                        .HasColumnType("date")
                        .HasColumnName("onboarding_date");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Segment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("segment");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CrmExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_customers_crm_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_customers_is_active");

                    b.HasIndex("Segment")
                        .HasDatabaseName("idx_customers_segment");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<string>("CrmExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_external_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Direction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("InteractionDate")
                        .HasColumnType("date")
                        .HasColumnName("interaction_date");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sentiment");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("CrmExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_interactions_crm_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_interactions_customer_id");

                    b.HasIndex("Direction")
                        .HasDatabaseName("idx_interactions_direction");

                    b.HasIndex("InteractionDate")
                        .HasDatabaseName("idx_interactions_interaction_date");

                    b.HasIndex("Sentiment")
                        .HasDatabaseName("idx_interactions_sentiment");

                    b.ToTable("interactions", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CrmExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_external_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CrmExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_invoices_crm_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_invoices_customer_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("idx_invoices_due_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_invoices_status");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CrmExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_external_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DaysLate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("days_late");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.HasKey("Id");

                    b.HasIndex("CrmExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_crm_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_payments_customer_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_payments_invoice_id");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("idx_payments_payment_date");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AvgChurnScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_churn_score");

                    b.Property<decimal>("AvgMarginScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_margin_score");

                    b.Property<decimal>("AvgPaymentScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_payment_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("GreenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("green_count");

                    b.Property<decimal>("GreenPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("green_pct");

                    b.Property<int>("RedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("red_count");

                    b.Property<decimal>("RedPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("red_pct");

                    b.Property<string>("SegmentBreakdown")
                        .HasColumnType("jsonb")
                        .HasColumnName("segment_breakdown");

                    b.Property<int>("TotalCustomers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_customers");

                    b.Property<int>("YellowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("yellow_count");

                    b.Property<decimal>("YellowPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("yellow_pct");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_portfolio_snapshots_created_at");

                    b.ToTable("portfolio_snapshots", (string)null);
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.RiskExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("confidence");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("claude-sonnet-4-6")
                        .HasColumnName("model_used");

                    b.Property<Guid>("RiskScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_score_id");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_risk_explanations_customer_id");

                    b.HasIndex("RiskScoreId")
                        .HasDatabaseName("idx_risk_explanations_risk_score_id");

                    b.HasIndex("RiskType")
                        .HasDatabaseName("idx_risk_explanations_risk_type");

                    b.ToTable("risk_explanations", null, t =>
                        {
                            t.HasCheckConstraint("chk_confidence_values", "confidence IN ('high', 'medium', 'low')");

                            t.HasCheckConstraint("chk_risk_type_values", "risk_type IN ('churn', 'payment', 'margin', 'overall')");
                        });
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.RiskScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChurnScore")
                        .HasColumnType("integer")
                        .HasColumnName("churn_score");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("HeatLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("heat_level");

                    b.Property<int>("MarginScore")
                        .HasColumnType("integer")
                        .HasColumnName("margin_score");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<int>("PaymentScore")
                        .HasColumnType("integer")
                        .HasColumnName("payment_score");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_risk_scores_customer_id");

                    b.HasIndex("HeatLevel")
                        .HasDatabaseName("idx_risk_scores_heat_level");

                    b.HasIndex("OverallScore")
                        .IsDescending()
                        .HasDatabaseName("idx_risk_scores_overall_score");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("idx_risk_scores_snapshot_id");

                    b.ToTable("risk_scores", null, t =>
                        {
                            t.HasCheckConstraint("chk_churn_score_range", "churn_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("chk_heat_level_values", "heat_level IN ('green', 'yellow', 'red')");

                            t.HasCheckConstraint("chk_margin_score_range", "margin_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("chk_overall_score_range", "overall_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("chk_payment_score_range", "payment_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.SuggestedAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<Guid>("RiskScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_score_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_suggested_actions_customer_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_suggested_actions_priority");

                    b.HasIndex("RiskScoreId")
                        .HasDatabaseName("idx_suggested_actions_risk_score_id");

                    b.ToTable("suggested_actions", null, t =>
                        {
                            t.HasCheckConstraint("chk_action_type_values", "action_type IN ('outreach', 'discount', 'review', 'escalate', 'upsell')");

                            t.HasCheckConstraint("chk_priority_values", "priority IN ('high', 'medium', 'low')");
                        });
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Complaint", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Contract", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Interaction", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("Interactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Invoice", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Payment", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioThermometer.Core.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.RiskExplanation", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("RiskExplanations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioThermometer.Core.Models.RiskScore", "RiskScore")
                        .WithMany("RiskExplanations")
                        .HasForeignKey("RiskScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RiskScore");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.RiskScore", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("RiskScores")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioThermometer.Core.Models.PortfolioSnapshot", "Snapshot")
                        .WithMany("RiskScores")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.SuggestedAction", b =>
                {
                    b.HasOne("PortfolioThermometer.Core.Models.Customer", "Customer")
                        .WithMany("SuggestedActions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioThermometer.Core.Models.RiskScore", "RiskScore")
                        .WithMany("SuggestedActions")
                        .HasForeignKey("RiskScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RiskScore");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Customer", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Contracts");

                    b.Navigation("Interactions");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("RiskExplanations");

                    b.Navigation("RiskScores");

                    b.Navigation("SuggestedActions");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.PortfolioSnapshot", b =>
                {
                    b.Navigation("RiskScores");
                });

            modelBuilder.Entity("PortfolioThermometer.Core.Models.RiskScore", b =>
                {
                    b.Navigation("RiskExplanations");

                    b.Navigation("SuggestedActions");
                });
#pragma warning restore 612, 618
        }
    }
}
