import { TitleCasePipe } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RiskExplanation, RiskType } from '../../../core/models/risk-explanation.model';
import { HeatBadgeComponent } from '../../../shared/components/heat-badge/heat-badge.component';
import { HeatLevel } from '../../../core/models/risk-score.model';

const TABS: { value: RiskType; label: string }[] = [
  { value: 'churn', label: 'Churn' },
  { value: 'payment', label: 'Payment' },
  { value: 'margin', label: 'Margin' },
  { value: 'overall', label: 'Overall' },
];

const CONFIDENCE_COLOR: Record<string, string> = {
  high: 'var(--color-green)',
  medium: 'var(--color-yellow)',
  low: 'var(--color-text-muted)',
};

@Component({
  selector: 'app-explanation-panel',
  standalone: true,
  imports: [HeatBadgeComponent, TitleCasePipe],
  template: `
    <div class="panel">
      <div class="panel__tabs">
        @for (tab of tabs; track tab.value) {
          <button
            class="tab"
            [class.tab--active]="activeTab === tab.value"
            (click)="activeTab = tab.value"
          >{{ tab.label }}</button>
        }
      </div>

      @if (active) {
        <div class="panel__content">
          <div class="panel__meta">
            <app-heat-badge [heatLevel]="scoreHeat" />
            <span class="panel__confidence" [style.color]="confidenceColor">
              {{ active.confidence | titlecase }} confidence
            </span>
            <span class="panel__ai-label">
              <span class="panel__ai-icon">✨</span>
              AI Advisory
              <span class="panel__info" title="Risk scores are computed by deterministic rules. This explanation is AI-generated by {{ active.modelUsed }} and is advisory only.">ⓘ</span>
            </span>
          </div>
          <p class="panel__text">{{ active.explanation }}</p>
        </div>
      } @else {
        <p class="panel__empty">No explanation available for this risk dimension.</p>
      }
    </div>
  `,
  styles: [`
    .panel {
      &__tabs {
        display: flex;
        gap: 4px;
        border-bottom: 1px solid var(--color-border);
        margin-bottom: 20px;
      }

      &__content {
        display: flex;
        flex-direction: column;
        gap: 12px;
      }

      &__meta {
        display: flex;
        align-items: center;
        gap: 12px;
        flex-wrap: wrap;
      }

      &__confidence {
        font-size: 12px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.04em;
      }

      &__ai-label {
        margin-left: auto;
        font-size: 11px;
        font-weight: 800;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: #7c3aed;
        display: inline-flex;
        align-items: center;
        gap: 4px;
        background: linear-gradient(135deg, rgba(124, 58, 237, 0.12), rgba(79, 70, 229, 0.10));
        border: 1px solid rgba(124, 58, 237, 0.25);
        border-radius: 999px;
        padding: 3px 10px;
      }

      &__ai-icon { font-size: 13px; }

      &__info {
        cursor: help;
        font-size: 14px;
      }

      &__text {
        font-size: 14px;
        line-height: 1.7;
        color: var(--color-text);
        max-width: 680px;
      }

      &__empty {
        color: var(--color-text-muted);
        font-size: 13px;
        padding: 16px 0;
      }
    }

    .tab {
      padding: 8px 14px;
      font-size: 13px;
      font-weight: 600;
      border: none;
      border-bottom: 2px solid transparent;
      background: transparent;
      color: var(--color-text-muted);
      cursor: pointer;
      transition: all var(--duration-fast);
      margin-bottom: -1px;

      &:hover { color: var(--color-text); }

      &--active {
        color: var(--color-text);
        border-bottom-color: var(--color-text);
      }
    }
  `],
})
export class ExplanationPanelComponent {
  @Input() explanations: RiskExplanation[] = [];
  @Input() overallScore = 0;

  activeTab: RiskType = 'churn';
  readonly tabs = TABS;

  get active(): RiskExplanation | undefined {
    return this.explanations.find(e => e.riskType === this.activeTab);
  }

  get scoreHeat(): HeatLevel {
    const score = this.overallScore;
    if (score >= 70) return 'red';
    if (score >= 40) return 'yellow';
    return 'green';
  }

  get confidenceColor(): string {
    return CONFIDENCE_COLOR[this.active?.confidence ?? 'low'];
  }
}
